#!/usr/bin/env perl

use strict;
use warnings;
use Path::Tiny;

my $dir = shift(@ARGV);

my $out = << 'EOF';
/*
 * DO NOT EDIT! generated by embed_mruby_code.pl
 * Please refer to the respective source files for copyright information.
 */

EOF

path($dir)->visit(sub {
    my ($path, $state) = @_;
    return if $path->is_dir;
    return unless $path =~ /\.rb$/;
    my @lines = $path->lines({ chomp => 1 });

    @lines = map {
        s/\x5c/\\\\/g;
        s/\x22/\\"/g;
        $_;
    } @lines;

    my $name = uc($path->basename('.rb'));

    $out .= "/* $path */\n";
    $out .= "#define H2GET_MRUBY_PATH_$name \"$path\"\n";
    $out .= "#define H2GET_MRUBY_CODE_$name \\\n";
    $out .= join("\n", map { '"' . $_ . '\\n" \\' } @lines);
    $out .= "\n\n";
}, +{ recurse => 1 });

# for my $path (map { path($_) } grep { $_ =~ /\.rb$/ } @dir) {
# }
print $out;
