/*
 * DO NOT EDIT! generated by embed_mruby_code.pl
 * Please refer to the respective source files for copyright information.
 */

/* mrblib/h2.rb */
#define H2GET_MRUBY_PATH_H2 "mrblib/h2.rb"
#define H2GET_MRUBY_CODE_H2 \
"class H2\n" \
"  attr_reader :current_conn\n" \
"\n" \
"  [\n" \
"    :expect_prefix,\n" \
"    :send_prefix,\n" \
"    :expect_prefix,\n" \
"    :send_prefix,\n" \
"    :send_settings,\n" \
"    :send_settings_ack,\n" \
"    :send_priority,\n" \
"    :send_ping,\n" \
"    :send_rst_stream,\n" \
"    :send_window_update,\n" \
"    :send_goaway,\n" \
"    :send_raw_frame,\n" \
"    :get,\n" \
"    :getp,\n" \
"    :send_headers,\n" \
"    :send_data,\n" \
"    :send_continuation,\n" \
"    :on_settings,\n" \
"    :read,\n" \
"    :close,\n" \
"  ].each do |meth|\n" \
"    define_method(meth) do |*args|\n" \
"      if @current_conn.nil?\n" \
"        raise 'no available connection'\n" \
"      end\n" \
"      @current_conn.send(meth, *args)\n" \
"    end\n" \
"  end\n" \
"end\n" \

/* mrblib/h2conn.rb */
#define H2GET_MRUBY_PATH_H2CONN "mrblib/h2conn.rb"
#define H2GET_MRUBY_CODE_H2CONN \
"class H2Conn\n" \
"  attr_reader :addr\n" \
"  \n" \
"end\n" \

